import {describe, expect, it} from 'vitest';
import type {
  AttributionControlInstance,
  AttributionControlOptions,
  BackgroundLayerSpecification,
  CanvasSourceSpecification,
  CircleLayerSpecification,
  ControlPosition,
  CustomLayerInterface,
  FillExtrusionLayerSpecification,
  FillLayerSpecification,
  FullscreenControlInstance,
  FullscreenControlOptions,
  GeolocateControlInstance,
  GeolocateControlOptions,
  GeolocateErrorEvent,
  GeolocateEvent,
  GeolocateResultEvent,
  GeoJSONSourceSpecification,
  GlobeControlInstance,
  HeatmapLayerSpecification,
  HillshadeLayerSpecification,
  IControl,
  ImageSourceSpecification,
  LayerSpecification,
  LightSpecification,
  LineLayerSpecification,
  LngLat,
  LngLatBounds,
  LngLatBoundsLike,
  LngLatLike,
  LogoControlInstance,
  LogoControlOptions,
  MapBoxZoomEvent,
  MapCallbacks,
  MapEvent,
  MapGeoJSONFeature,
  MapInstance,
  MapLayerMouseEvent,
  MapLayerTouchEvent,
  MapLibreEvent,
  MapLib,
  MapMouseEvent,
  MapOptions,
  MapRef,
  MapSourceDataEvent,
  MapStyleDataEvent,
  MapTouchEvent,
  MapTouchLikeEvent,
  MapWheelEvent,
  MarkerDragEvent,
  MarkerEvent,
  MarkerInstance,
  MarkerOptions,
  NavigationControlInstance,
  NavigationControlOptions,
  PaddingOptions,
  Point,
  PointLike,
  PopupEvent,
  PopupInstance,
  PopupOptions,
  ProjectionSpecification,
  RasterDEMSourceSpecification,
  RasterLayerSpecification,
  RasterSourceSpecification,
  ScaleControlInstance,
  ScaleControlOptions,
  SkySpecification,
  SourceSpecification,
  StyleSpecification,
  SymbolLayerSpecification,
  TerrainControlInstance,
  TerrainSpecification,
  VectorSourceSpecification,
  VideoSourceSpecification,
  ViewState
} from '../src';

type PublicCommonExports = [
  Point,
  PointLike,
  LngLat,
  LngLatLike,
  LngLatBounds,
  LngLatBoundsLike,
  PaddingOptions,
  MapGeoJSONFeature,
  ViewState
];

type PublicEventExports = [
  MapEvent,
  MapLibreEvent,
  MapMouseEvent,
  MapLayerMouseEvent,
  MapTouchEvent,
  MapLayerTouchEvent,
  MapTouchLikeEvent,
  MapStyleDataEvent,
  MapSourceDataEvent,
  MapWheelEvent,
  MapBoxZoomEvent,
  MapCallbacks,
  PopupEvent,
  MarkerEvent,
  MarkerDragEvent,
  GeolocateEvent,
  GeolocateResultEvent,
  GeolocateErrorEvent
];

type PublicLibExports = [
  ControlPosition,
  CustomLayerInterface,
  IControl,
  MapInstance,
  MapOptions,
  MapRef,
  MapLib,
  MarkerInstance,
  MarkerOptions,
  PopupInstance,
  PopupOptions,
  AttributionControlInstance,
  AttributionControlOptions,
  FullscreenControlInstance,
  FullscreenControlOptions,
  GeolocateControlInstance,
  GeolocateControlOptions,
  NavigationControlInstance,
  NavigationControlOptions,
  ScaleControlInstance,
  ScaleControlOptions,
  TerrainControlInstance,
  TerrainSpecification,
  LogoControlInstance,
  LogoControlOptions,
  GlobeControlInstance
];

type PublicStyleSpecExports = [
  LayerSpecification,
  FillLayerSpecification,
  LineLayerSpecification,
  SymbolLayerSpecification,
  CircleLayerSpecification,
  HeatmapLayerSpecification,
  FillExtrusionLayerSpecification,
  RasterLayerSpecification,
  HillshadeLayerSpecification,
  BackgroundLayerSpecification,
  SourceSpecification,
  VectorSourceSpecification,
  RasterSourceSpecification,
  RasterDEMSourceSpecification,
  GeoJSONSourceSpecification,
  VideoSourceSpecification,
  ImageSourceSpecification,
  CanvasSourceSpecification,
  StyleSpecification,
  SkySpecification,
  LightSpecification,
  ProjectionSpecification
];

type PublicTypeExports = [
  PublicCommonExports,
  PublicEventExports,
  PublicLibExports,
  PublicStyleSpecExports
];

describe('public type exports', () => {
  it('keeps upstream-compatible type aliases exported from the package entry', () => {
    const typeCheckOnly: PublicTypeExports | null = null;

    expect(typeCheckOnly).toBeNull();
  });
});
