export type {
  BackgroundLayerSpecification,
  CanvasSourceSpecification,
  CircleLayerSpecification,
  FillExtrusionLayerSpecification,
  FillLayerSpecification,
  GeoJSONSourceSpecification,
  HeatmapLayerSpecification,
  HillshadeLayerSpecification,
  ImageSourceSpecification,
  LayerSpecification,
  LightSpecification,
  LineLayerSpecification,
  ProjectionSpecification,
  RasterDEMSourceSpecification,
  RasterLayerSpecification,
  RasterSourceSpecification,
  SkySpecification,
  SourceSpecification,
  StyleSpecification,
  SymbolLayerSpecification,
  TerrainSpecification,
  VectorSourceSpecification,
  VideoSourceSpecification
} from 'maplibre-gl';
